apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ymvt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ymvt
    app.kubernetes.io/part-of: tkrw-pr712-0075-0005-app
  name: devfile-sample-ymvt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ymvt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ymvt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-ymvt@sha256:ee67a3fd4252fdd5e3e8739b2ae8dd963e47f18c5ca0fefa663560c07f509a5a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
